### ISSUE TITLE
MergeMethodDefinitionTest#testGetWhere() slow 

### ISSUE THREAD

**Issue by jakobbraun** [exasol/sql-statement-builder#103]
MergeMethodDefinitionTest#testGetWhere() takes > 1s. I was wonering if this is intended...

**Comment by pj-spoelders** [comment]
So I took a closer look at this. The first time one of the tests in this `MergeMethodDefinitionTest` test class run it takes about 500ms. The other 2 executed afterwards will run way faster (in the 1-3ms range).
I did time the `beforeEach` and the `testGetWhere` itself and the `beforeEach` took <1 ms and the `testGetWhere` took about 3ms.
So it's clear the tests and the code being tested are plenty fast.

I think it has something to do with the test framework setting things up, maybe the generated test class constructor? I propose to close this issue.

**Comment by jakobbraun** [comment]
ok
