### ISSUE TITLE
Refactor ValueTableVisitor

### ISSUE THREAD

**Issue by kaklakariada** [exasol/sql-statement-builder#125]
Refactor the ValueTableVisitor interface like ColumnsDefinitionRenderer (#102) or BooleanExpressionVisitor (#100).

**Comment by redcatbear** [comment]
I gave this one a shot and realized that, while with the previous refactorings the classes got smaller, we lost runtime efficiency and diluted the design (e.g. where SoC is broken now). So it looks like the whole visitor structure will need a clean redesign. Preferably done in pair programming mode.

**Comment by kaklakariada** [comment]
We don't have the capacity to implement this at the moment.
