### ISSUE TITLE
Support multiple columns in ORDER BY clause

### ISSUE THREAD

**Issue by kaklakariada** [exasol/sql-statement-builder#127]
**Is your feature request related to a problem? Please describe.**
I want to specify multiple columns in an `ORDER BY` clause.

**Describe the solution you'd like**
Rendering a `SELECT` statement and `OVER` clause should support multiple columns in an `ORDER BY` clause as defined in the [documentation](https://docs.exasol.com/sql/select.htm).

**Comment by redcatbear** [comment]
Shelved, because not in roadmap focus.
