### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by morazow** [exasol/sql-statement-builder#14]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to use the sql-statement-builder by including as a dependency from another project.

**Describe alternatives you've considered**
None.

**Additional context**
Should be released to [maven central](https://mvnrepository.com/artifact/com.exasol) and easy to reference from another project.

**Comment by redcatbear** [comment]
Done already.
