### ISSUE TITLE
Fix JavaDoc in combination with Java 11

### ISSUE THREAD

**Issue by redcatbear** [exasol/sql-statement-builder#19]
# Description
When running a Travis CI build with Java 11 we get the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project sql-statement-builder: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] 
[ERROR] Command line was: /home/travis/openjdk11/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/travis/build/exasol/sql-statement-builder/target/apidocs' dir.
```

## Steps to Reproduce
1. Enable OpenJDK11 in `.travis.yml`
2. Run build in Travis CI

## Expected behavior
Build succeeds.

# Environment
- SQL Statement Builder: 0.3.0 SNAPSHOT
- Java Version: openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by AnastasiiaSergienko** [comment]
Fixed after porting to java 11 #82
