### ISSUE TITLE
Example in Readme broken

### ISSUE THREAD

**Issue by jakobbraun** [exasol/sql-statement-builder#61]
in the example in the README.md in line `StringRendererConfig.builder().useQuotes().build();` the `useQuotes()` method does not exist.

**Comment by jakobbraun** [comment]
looks like the method was renamed to `quoteIdentifiers()`

**Comment by jakobbraun** [comment]
there seems to be some more things broken in this example...

**Comment by AnastasiiaSergienko** [comment]
Closed with #73
