### ISSUE TITLE
Add support for special cases of scalar functions

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/sql-statement-builder#68]
Currently unsupported or partly supported scalar function:

#### String Functions:

- POSITION https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/position.htm#POSITION
- SUBSTR (partly supported without key words) https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/substr[ing].htm#SUBSTR[ING]
- TRIM (partly supported without key words) https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/trim.htm#TRIM

 #### Date/Time Functions:

- ADD_ functions (can contain keywords, supported without them now)
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/add_days.htm#ADD_DAYS
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/add_hour.htm#ADD_HOUR
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/add_minutes.htm#ADD_MINUTES
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/add_months.htm#ADD_MONTHS
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/add_seconds.htm#ADD_SECONDS
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/add_weeks.htm#ADD_WEEKS
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/add_years.htm#ADD_YEARS

- CONVERT_TZ (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/convert_tz.htm#CONVERT_TZ

- DATE_TRUNC
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/date_trunc.htm#DATE_TRUNC

- DAY (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/day.htm#DAY

- _BETWEEN functions (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/days_between.htm#DAYS_BETWEEN
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/hours_between.htm#HOURS_BETWEEN
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/minutes_between.htm#MINUTES_BETWEEN
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/month_between.htm#MONTH_BETWEEN
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/seconds_between.htm#SECONDS_BETWEEN
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/years_between.htm#YEARS_BETWEEN

- EXTRACT 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/extract.htm#EXTRACT

- HOUR (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/hour.htm#HOUR

- MINUTE  (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/minute.htm#MINUTE

- MONTH  (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/month.htm#MONTH

- WEEK
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/week.htm#WEEK

- YEAR (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/year.htm#YEAR

- ROUND
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/round%20(datetime).htm#ROUND_(datetime)

- SECOND  (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/second.htm#SECOND

 #### Conversion Functions:

- CAST
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/cast.htm#CAST

- CONVERT
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/convert.htm#CONVERT

- TO_CHAR (datetime) (can contain keywords, supported without them now) 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/to_char%20(datetime).htm#TO_CHAR_(datetime)

####  Functions for Hierarchical Queries:
 
- CONNECT_BY_ISCYCLE, CONNECT_BY_ISLEAF, LEVEL, SYS_CONNECT_BY_PATH
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/sys_connect_by_path.htm#SYS_CONNECT_BY_PATH

#### Other Scalar Functions

- CASE 
https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/case.htm#CASE

- SPACE https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/space.htm#SPACE

We need to decide which of them we want to support and implement them if needed.

**Comment by redcatbear** [comment]
Shelved, because not in roadmap focus.
